"""add free space indicator

Revision ID: 5f72e9e0fa9f
Revises: 99266bec8276
Create Date: 2017-04-13 12:08:43.120061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f72e9e0fa9f'
down_revision = '99266bec8276'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('free_space', sa.BigInteger(), nullable=True))
    op.alter_column('monitoringrequest', 'request_token',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('torrentrequest', 'request_token',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('torrentrequest', 'request_token',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('monitoringrequest', 'request_token',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('client', 'free_space')
    ### end Alembic commands ###
